DATA SEGMENT
    MSG1 DB 10,13,'ENTER NO. OF ELEMENTS: $'
    MSG2 DB 10,13,'ENTER SEARCH ELEMENT: $'
    MSG3 DB 10,13,'ENTER A NUMBER IN LIST: $'
    MSG4 DB 10,13,'ELEMENT FOUND AT LOCATION $'
    MSG5 DB 10,13,'ELEMENT NOT FOUND $'
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    MOV SI, 3000H
    LEA DX, MSG1
    MOV AH, 9H
    INT 21H
    MOV AH, 01H
    INT 21H
    SUB AL, 30H
    MOV AH, 00H
    MOV CX, AX
    MOV SP, CX
    LEA DX, MSG2
    MOV AH, 9H
    INT 21H
    CALL INPUTNUM
    MOV BX, DX
    MOV DI, 00H

USERINPUTLIST:
    LEA DX, MSG3
    MOV AH, 9H
    INT 21H
    CALL INPUTNUM
    MOV [SI], DX
    ADD SI, 02H
    LOOP USERINPUTLIST
    MOV SI, 3000H
    MOV CX, SP

SEARCHING:
    MOV AX, [SI]
    CMP AX, BX
    JE FOUND
    ADD SI, 02H
    INC DI
    LOOP SEARCHING

NOTFOUND:
    LEA DX, MSG5
    MOV AH, 9H
    INT 21H
    JMP XX

FOUND:
    LEA DX, MSG4
    MOV AH, 9H
    INT 21H
    MOV DX, DI
    ADD DL, 30H
    MOV AH, 02H
    INT 21H

XX:
    MOV AH,4CH
    INT 21H
    INPUTNUM PROC
    PUSH CX
    PUSH BX
    PUSH AX
    MOV CX, 10H
    MOV DX, 00H

INPUT:
    MOV AH, 01H
    INT 21H
    CMP AL, 0DH
    JE DONE
    SUB AL, 30H
    MOV AH, 00H
    MOV BX, AX
    MOV AX, DX
    MUL CX
    ADD AX, BX
    MOV DX, AX
    JMP INPUT 

DONE:
    POP AX
    POP BX
    POP CX
    RET

INPUTNUM ENDP
CODE ENDS
END START